#!/usr/bin/env bash
set -euo pipefail

CLI_PREFIX=${RUN_AGENT_CLI_PREFIX:-/root/.local}
export PATH="${CLI_PREFIX}/bin:${PATH}"
export npm_config_prefix="${CLI_PREFIX}"
export NPM_CONFIG_PREFIX="${CLI_PREFIX}"

# Detect if running in Docker environment
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IS_DOCKER=false
if [[ "$SCRIPT_DIR" == /app* ]] || [[ -d /app ]]; then
  IS_DOCKER=true
fi

AGENT=${1:-}
if [[ -z "$AGENT" ]]; then
  echo "[run-agent] Missing agent name" >&2
  exit 1
fi
shift || true

ensure_node_cli() {
  local bin_name="$1"
  local package_name="$2"

  if [[ "$IS_DOCKER" == "true" ]]; then
    # In Docker: always install/upgrade to latest
    echo "[run-agent] Installing/upgrading ${bin_name} (package: ${package_name})" >&2
    # Uninstall first to avoid npm upgrade conflicts with cached packages
    npm uninstall -g --prefix "$CLI_PREFIX" "$package_name" 2>/dev/null || true
    npm install -g --prefix "$CLI_PREFIX" "$package_name"
  else
    # Local: only install if not present
    if command -v "$bin_name" >/dev/null 2>&1; then
      return 0
    fi
    echo "[run-agent] Installing ${bin_name} (package: ${package_name})" >&2
    npm install -g --prefix "$CLI_PREFIX" "$package_name"
  fi
}

case "$AGENT" in
  aider)
    if [[ "$IS_DOCKER" == "true" ]] || ! command -v "aider" >/dev/null 2>&1; then
      echo "[run-agent] Installing/upgrading aider via official script" >&2
      curl -LsSf https://aider.chat/install.sh | bash
    fi
    exec aider "$@"
    ;;
  goose)
    if [[ "$IS_DOCKER" == "true" ]] || ! command -v "goose" >/dev/null 2>&1; then
      echo "[run-agent] Installing/upgrading goose CLI" >&2
      env CONFIGURE=false curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | bash
    fi
    exec goose "$@"
    ;;
  cursor | cursor-agent)
    if [[ "$IS_DOCKER" == "true" ]] || ! command -v "cursor-agent" >/dev/null 2>&1; then
      echo "[run-agent] Installing/upgrading cursor agent" >&2
      curl -fsS https://cursor.com/install | bash
    fi
    exec cursor-agent "$@"
    ;;
  opencode)
    ensure_node_cli "opencode" "opencode-ai"
    exec opencode "$@"
    ;;
  codex)
    ensure_node_cli "codex" "@openai/codex"
    # Ensure Codex config.toml exists (required for model providers)
    CODEX_CONFIG_DIR="${HOME}/.codex"
    CODEX_CONFIG_PATH="${CODEX_CONFIG_DIR}/config.toml"
    if [[ ! -f "$CODEX_CONFIG_PATH" ]]; then
      echo "[run-agent] Creating Codex config.toml at $CODEX_CONFIG_PATH" >&2
      mkdir -p "$CODEX_CONFIG_DIR"
      cat > "$CODEX_CONFIG_PATH" << 'EOF'
# Auto-generated by run-agent.sh
[model_providers.openai]
name = "OpenAI"
base_url = "https://api.openai.com/v1"
env_key = "OPENAI_API_KEY"

[model_providers.anthropic]
name = "Anthropic"
base_url = "https://api.anthropic.com/v1"
env_key = "ANTHROPIC_API_KEY"

[model_providers.cerebras]
name = "Cerebras"
base_url = "https://api.cerebras.ai/v1"
env_key = "CEREBRAS_API_KEY"

[model_providers.groq]
name = "Groq"
base_url = "https://api.groq.com/openai/v1"
env_key = "GROQ_API_KEY"

[model_providers.openrouter]
name = "OpenRouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"
EOF
    fi
    exec codex "$@"
    ;;
  claude)
    ensure_node_cli "claude" "@anthropic-ai/claude-code"
    exec claude "$@"
    ;;
  gemini)
    ensure_node_cli "gemini" "@google/gemini-cli"
    exec gemini "$@"
    ;;
  qwen)
    ensure_node_cli "qwen" "@qwen-code/qwen-code"
    exec qwen "$@"
    ;;
  *)
    if command -v "$AGENT" >/dev/null 2>&1; then
      exec "$AGENT" "$@"
    fi

    echo "[run-agent] Unsupported agent '${AGENT}'. Please install the CLI manually." >&2
    exit 1
    ;;
 esac
